[450] Added additional checkboxes to "Universign::Document"
CapSens/Universign pull request #17
Opened 2023-05-04 12:49 UTC by SLegrez

J'ai fait une carte spécifique pour ça -> [Trello](https://trello.com/c/AUGF892o/450-ajouter-des-checkboxs-sur-le-document-universign)

C'est testé en ne renseignant pas `check_box_texts` :
![Capture d’écran 2023-05-04 à 14 48 01](https://user-images.githubusercontent.com/65570378/236209139-44d72bce-ae68-4f66-8e02-81c117322734.png)

En en rajoutant 2 :
![Capture d’écran 2023-05-04 à 14 48 16](https://user-images.githubusercontent.com/65570378/236209181-ee821c8b-0a4b-4524-97cd-a577405d77da.png)

2023-05-05 07:52 UTC, Kernael approved these changes

2023-05-09 10:03 UTC, AntoineBecquet reviewed
+1 pour la version et le changelog. Tu peux mettre un exemple dans le README aussi ?

2023-05-09 10:03 UTC, AntoineBecquet commented on lib/universign/version.rb
> +  VERSION = "1.5.2"
C'est pas un gros changement, mais si on suit le semantic versioning, c'est une nouvelle fonctionnalité donc `1.6.0`.

https://semver.org/

2023-05-09 10:03 UTC, AntoineBecquet requested changes
mauvais bouton

2023-05-09 12:40 UTC, SLegrez commented
J'ai supprimé le tag `v.1.5.2` en local et en remote, pushé le nouvellement créé tag `v1.6.0` et ajouté un exemple dans le Readme ce qui fait que l'on passe de ça :
![Capture d’écran 2023-05-09 à 14 38 02](https://github.com/CapSens/Universign/assets/65570378/dd8c410d-5438-4158-9de1-fa959eeba918)

à ça :
![Capture d’écran 2023-05-09 à 14 40 28](https://github.com/CapSens/Universign/assets/65570378/65378f7c-8ebf-4379-a375-227d378c78d0)

2023-05-11 08:51 UTC, AntoineBecquet approved these changes

2023-05-11 08:56 UTC, merged